apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: watchdog
  namespace: openshift-watchdog
  labels:
    k8s-app: watchdog
spec:
  selector:
    matchLabels:
      name: watchdog
  template:
    metadata:
      labels:
        name: watchdog
    spec:
      tolerations:
      # this toleration is to have the daemonset runnable on master nodes
      # remove it if your masters can't run pods
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      containers:
      - name: watchdog
        image: quay.io/ricardoalonsos/watchdog:latest
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 50Mi
        securityContext:
          privileged: true
          runAsUser: 0
        volumeMounts:
        - name: dev-watchdog
          mountPath: /dev/watchdog
        - name: dev-watchdog0
          mountPath: /dev/watchdog0
      serviceAccount: watchdog
      serviceAccountName: watchdog
      terminationGracePeriodSeconds: 30
      volumes:
      - name: dev-watchdog
        hostPath:
          path: /dev/watchdog
          type: CharDevice
      - name: dev-watchdog0
        hostPath:
          path: /dev/watchdog0
          type: CharDevice
