apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: watchdog
  namespace: openshift-watchdog
  labels:
    k8s-app: watchdog
spec:
  selector:
    matchLabels:
      name: watchdog
  template:
    metadata:
      labels:
        name: watchdog
      annotations:
        openshift.io/scc: privileged
    spec:
      tolerations:
      # this toleration is to have the daemonset runnable on master nodes
      # remove it if your masters can't run pods
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      containers:
      - name: watchdog
        image: quay.io/ricardoalonsos/watchdog:latest
        securityContext:
          privileged: true
          runAsUser: 0
      hostNetwork: true
      serviceAccount: watchdog
      serviceAccountName: watchdog
      terminationGracePeriodSeconds: 30
